/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: LPC845
package_id: LPC845M301JBD48
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: '6', pin_signal: PIO0_4/ADC_11, label: TECLA_USR, identifier: TECLA_USR}
- {pin_num: '4', pin_signal: PIO0_12, label: TECLA_ISP, identifier: TECLA_ISP}
- {pin_num: '11', pin_signal: PIO1_0/CAPT_X1, label: LED_VERDE, identifier: LED_VERDE}
- {pin_num: '14', pin_signal: PIO1_1/CAPT_X2, label: LED_AZUL, identifier: LED_AZUL}
- {pin_num: '16', pin_signal: PIO1_2/CAPT_X3, label: LED_ROJO, identifier: LED_ROJO}
- {pin_num: '47', pin_signal: PIO0_18/ADC_8, label: PIN_RST_7SEG, identifier: PIN_RST_7SEG}
- {pin_num: '46', pin_signal: PIO0_19/ADC_7, label: PIN_CK_7SEG, identifier: PIN_CK_7SEG}
- {pin_num: '45', pin_signal: PIO0_20/ADC_6, label: PIN_BCD_A, identifier: PIN_BCD_A}
- {pin_num: '44', pin_signal: PIO0_21/ADC_5, label: PIN_BCD_D, identifier: PIN_BCD_D}
- {pin_num: '43', pin_signal: PIO0_22/ADC_4, label: PIN_BCD_C, identifier: PIN_BCD_C}
- {pin_num: '39', pin_signal: PIO0_23/ADC_3/ACMP_I4, label: PIN_BCD_B, identifier: PIN_BCD_B}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '6', peripheral: GPIO, signal: 'PIO0, 4', pin_signal: PIO0_4/ADC_11, direction: INPUT}
  - {pin_num: '4', peripheral: GPIO, signal: 'PIO0, 12', pin_signal: PIO0_12, direction: INPUT}
  - {pin_num: '11', peripheral: GPIO, signal: 'PIO1, 0', pin_signal: PIO1_0/CAPT_X1, direction: OUTPUT, gpio_init_state: 'true', mode: inactive}
  - {pin_num: '14', peripheral: GPIO, signal: 'PIO1, 1', pin_signal: PIO1_1/CAPT_X2, direction: OUTPUT, gpio_init_state: 'true', mode: inactive}
  - {pin_num: '16', peripheral: GPIO, signal: 'PIO1, 2', pin_signal: PIO1_2/CAPT_X3, direction: OUTPUT, gpio_init_state: 'true', mode: inactive}
  - {pin_num: '47', peripheral: GPIO, signal: 'PIO0, 18', pin_signal: PIO0_18/ADC_8, direction: OUTPUT, mode: inactive}
  - {pin_num: '46', peripheral: GPIO, signal: 'PIO0, 19', pin_signal: PIO0_19/ADC_7, direction: OUTPUT, mode: inactive}
  - {pin_num: '45', peripheral: GPIO, signal: 'PIO0, 20', pin_signal: PIO0_20/ADC_6, direction: OUTPUT, mode: inactive}
  - {pin_num: '44', peripheral: GPIO, signal: 'PIO0, 21', pin_signal: PIO0_21/ADC_5, direction: OUTPUT, mode: inactive}
  - {pin_num: '43', peripheral: GPIO, signal: 'PIO0, 22', pin_signal: PIO0_22/ADC_4, direction: OUTPUT, mode: inactive}
  - {pin_num: '39', peripheral: GPIO, signal: 'PIO0, 23', pin_signal: PIO0_23/ADC_3/ACMP_I4, direction: OUTPUT, mode: inactive}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
    /* Enables clock for IOCON.: enable */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);
    /* Enables the clock for the GPIO1 module */
    CLOCK_EnableClock(kCLOCK_Gpio1);

    gpio_pin_config_t TECLA_USR_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_4 (pin 6)  */
    GPIO_PinInit(BOARD_INITPINS_TECLA_USR_GPIO, BOARD_INITPINS_TECLA_USR_PORT, BOARD_INITPINS_TECLA_USR_PIN, &TECLA_USR_config);

    gpio_pin_config_t TECLA_ISP_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_12 (pin 4)  */
    GPIO_PinInit(BOARD_INITPINS_TECLA_ISP_GPIO, BOARD_INITPINS_TECLA_ISP_PORT, BOARD_INITPINS_TECLA_ISP_PIN, &TECLA_ISP_config);

    gpio_pin_config_t PIN_RST_7SEG_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_18 (pin 47)  */
    GPIO_PinInit(BOARD_INITPINS_PIN_RST_7SEG_GPIO, BOARD_INITPINS_PIN_RST_7SEG_PORT, BOARD_INITPINS_PIN_RST_7SEG_PIN, &PIN_RST_7SEG_config);

    gpio_pin_config_t PIN_CK_7SEG_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_19 (pin 46)  */
    GPIO_PinInit(BOARD_INITPINS_PIN_CK_7SEG_GPIO, BOARD_INITPINS_PIN_CK_7SEG_PORT, BOARD_INITPINS_PIN_CK_7SEG_PIN, &PIN_CK_7SEG_config);

    gpio_pin_config_t PIN_BCD_A_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_20 (pin 45)  */
    GPIO_PinInit(BOARD_INITPINS_PIN_BCD_A_GPIO, BOARD_INITPINS_PIN_BCD_A_PORT, BOARD_INITPINS_PIN_BCD_A_PIN, &PIN_BCD_A_config);

    gpio_pin_config_t PIN_BCD_D_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_21 (pin 44)  */
    GPIO_PinInit(BOARD_INITPINS_PIN_BCD_D_GPIO, BOARD_INITPINS_PIN_BCD_D_PORT, BOARD_INITPINS_PIN_BCD_D_PIN, &PIN_BCD_D_config);

    gpio_pin_config_t PIN_BCD_C_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_22 (pin 43)  */
    GPIO_PinInit(BOARD_INITPINS_PIN_BCD_C_GPIO, BOARD_INITPINS_PIN_BCD_C_PORT, BOARD_INITPINS_PIN_BCD_C_PIN, &PIN_BCD_C_config);

    gpio_pin_config_t PIN_BCD_B_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_23 (pin 39)  */
    GPIO_PinInit(BOARD_INITPINS_PIN_BCD_B_GPIO, BOARD_INITPINS_PIN_BCD_B_PORT, BOARD_INITPINS_PIN_BCD_B_PIN, &PIN_BCD_B_config);

    gpio_pin_config_t LED_VERDE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO1_0 (pin 11)  */
    GPIO_PinInit(BOARD_INITPINS_LED_VERDE_GPIO, BOARD_INITPINS_LED_VERDE_PORT, BOARD_INITPINS_LED_VERDE_PIN, &LED_VERDE_config);

    gpio_pin_config_t LED_AZUL_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO1_1 (pin 14)  */
    GPIO_PinInit(BOARD_INITPINS_LED_AZUL_GPIO, BOARD_INITPINS_LED_AZUL_PORT, BOARD_INITPINS_LED_AZUL_PIN, &LED_AZUL_config);

    gpio_pin_config_t LED_ROJO_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO1_2 (pin 16)  */
    GPIO_PinInit(BOARD_INITPINS_LED_ROJO_GPIO, BOARD_INITPINS_LED_ROJO_PORT, BOARD_INITPINS_LED_ROJO_PIN, &LED_ROJO_config);

    IOCON->PIO[30] = ((IOCON->PIO[30] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO0_18_MODE_INACTIVE));

    IOCON->PIO[29] = ((IOCON->PIO[29] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO0_19_MODE_INACTIVE));

    IOCON->PIO[28] = ((IOCON->PIO[28] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO0_20_MODE_INACTIVE));

    IOCON->PIO[27] = ((IOCON->PIO[27] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO0_21_MODE_INACTIVE));

    IOCON->PIO[26] = ((IOCON->PIO[26] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO0_22_MODE_INACTIVE));

    IOCON->PIO[25] = ((IOCON->PIO[25] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO0_23_MODE_INACTIVE));

    IOCON->PIO[36] = ((IOCON->PIO[36] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO1_0_MODE_INACTIVE));

    IOCON->PIO[37] = ((IOCON->PIO[37] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO1_1_MODE_INACTIVE));

    IOCON->PIO[38] = ((IOCON->PIO[38] &
                       /* Mask bits to zero which are setting */
                       (~(IOCON_PIO_MODE_MASK)))

                      /* Selects function mode (on-chip pull-up/pull-down resistor control).: Inactive. Inactive (no
                       * pull-down/pull-up resistor enabled). */
                      | IOCON_PIO_MODE(PIO1_2_MODE_INACTIVE));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
