/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_18_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_19_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_20_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_21_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_22_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_23_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_0_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_1_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_2_MODE_INACTIVE 0x00u

/*! @name PIO0_4 (number 6), TECLA_USR
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TECLA_USR_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_TECLA_USR_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_TECLA_USR_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_TECLA_USR_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TECLA_USR_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_12 (number 4), TECLA_ISP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TECLA_ISP_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_TECLA_ISP_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_TECLA_ISP_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_TECLA_ISP_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TECLA_ISP_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO1_0 (number 11), LED_VERDE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_VERDE_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_VERDE_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_VERDE_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_LED_VERDE_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_VERDE_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO1_1 (number 14), LED_AZUL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_AZUL_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_AZUL_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_AZUL_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_LED_AZUL_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_AZUL_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO1_2 (number 16), LED_ROJO
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_ROJO_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_ROJO_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_ROJO_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_LED_ROJO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_ROJO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO0_18 (number 47), PIN_RST_7SEG
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PIN_RST_7SEG_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PIN_RST_7SEG_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_PIN_RST_7SEG_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_PIN_RST_7SEG_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PIN_RST_7SEG_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_19 (number 46), PIN_CK_7SEG
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PIN_CK_7SEG_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PIN_CK_7SEG_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_PIN_CK_7SEG_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_PIN_CK_7SEG_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PIN_CK_7SEG_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PIO0_20 (number 45), PIN_BCD_A
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PIN_BCD_A_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PIN_BCD_A_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_PIN_BCD_A_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_PIN_BCD_A_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PIN_BCD_A_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_21 (number 44), PIN_BCD_D
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PIN_BCD_D_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PIN_BCD_D_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_PIN_BCD_D_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_PIN_BCD_D_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PIN_BCD_D_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_22 (number 43), PIN_BCD_C
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PIN_BCD_C_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PIN_BCD_C_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_PIN_BCD_C_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_PIN_BCD_C_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PIN_BCD_C_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PIO0_23 (number 39), PIN_BCD_B
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PIN_BCD_B_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_PIN_BCD_B_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_PIN_BCD_B_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_PIN_BCD_B_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PIN_BCD_B_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
